'use strict';

/**
 * Builds a SYNTHETIC mdoc DeviceResponse for local testing (mock wallet and
 * unit tests). It is signed by a throw-away key/certificate generated on the
 * fly, so it proves nothing about real citizens - it only exercises the RP.
 */

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const { Encoder, Tag } = require('cbor-x');

const encoder = new Encoder({ useRecords: false, mapsAsObjects: false });
const enc = (v) => encoder.encode(v);

/** Self-signed P-256 issuer (acts as its own trust anchor). Needs the openssl CLI. */
function createTestIssuer(commonName = 'Sample RP Benin - TEST issuer') {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sample-rp-benin-'));
  try {
    execFileSync(
      'openssl',
      ['req', '-x509', '-newkey', 'ec', '-pkeyopt', 'ec_paramgen_curve:P-256', '-nodes',
        '-keyout', path.join(dir, 'k.pem'), '-out', path.join(dir, 'c.pem'),
        '-subj', `/CN=${commonName}`, '-days', '30'],
      { stdio: 'ignore' }
    );
    const certPem = fs.readFileSync(path.join(dir, 'c.pem'));
    return {
      key: crypto.createPrivateKey(fs.readFileSync(path.join(dir, 'k.pem'))),
      certPem,
      certDer: new crypto.X509Certificate(certPem).raw
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

const isFullDate = (v) => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v);

/**
 * @param {object} o
 * @param {string} o.docType
 * @param {string} o.namespace
 * @param {object} o.elements   { element_identifier: value }
 * @param {object} [o.issuer]   result of createTestIssuer() (omit => unsigned x5chain)
 * @param {Date}   [o.validFrom] / [o.validUntil]
 * @param {boolean} [o.tamper]  alter the first disclosed value after signing (negative test)
 * @returns {string} base64url DeviceResponse
 */
function buildDeviceResponse({ docType, namespace, elements, issuer, validFrom, validUntil, tamper }) {
  const now = Date.now();
  const items = Object.entries(elements).map(([id, value], digestID) => ({
    digestID,
    bytes: enc(new Map([
      ['digestID', digestID],
      ['random', crypto.randomBytes(16)],
      ['elementIdentifier', id],
      ['elementValue', isFullDate(value) ? new Tag(value, 1004) : value]
    ]))
  }));

  const valueDigests = new Map([[namespace, new Map(items.map((i) => [
    i.digestID,
    crypto.createHash('sha256').update(enc(new Tag(i.bytes, 24))).digest()
  ]))]]);

  const mso = new Map([
    ['version', '1.0'],
    ['digestAlgorithm', 'SHA-256'],
    ['valueDigests', valueDigests],
    ['deviceKeyInfo', new Map([['deviceKey', new Map([[1, 2], [-1, 1]])]])],
    ['docType', docType],
    ['validityInfo', new Map([
      ['signed', new Tag(new Date(now).toISOString().replace(/\.\d+Z/, 'Z'), 0)],
      ['validFrom', new Tag(new Date(validFrom || now - 3600e3).toISOString().replace(/\.\d+Z/, 'Z'), 0)],
      ['validUntil', new Tag(new Date(validUntil || now + 86400e3 * 30).toISOString().replace(/\.\d+Z/, 'Z'), 0)]
    ])]
  ]);

  // Tamper demo: the wallet "changes" a value after the issuer signed the digests.
  if (tamper) {
    const first = items[0];
    const m = new Map([
      ['digestID', first.digestID],
      ['random', crypto.randomBytes(16)],
      ['elementIdentifier', Object.keys(elements)[0]],
      ['elementValue', 'TAMPERED']
    ]);
    first.bytes = enc(m);
  }

  const payload = enc(new Tag(enc(mso), 24));
  const protectedBytes = enc(new Map([[1, -7]]));
  const unprotected = new Map();
  let signature = Buffer.alloc(64);
  if (issuer) {
    unprotected.set(33, issuer.certDer);
    const toSign = enc(['Signature1', protectedBytes, Buffer.alloc(0), payload]);
    signature = crypto.sign('sha256', toSign, { key: issuer.key, dsaEncoding: 'ieee-p1363' });
  }

  const response = new Map([
    ['version', '1.0'],
    ['documents', [new Map([
      ['docType', docType],
      ['issuerSigned', new Map([
        ['nameSpaces', new Map([[namespace, items.map((i) => new Tag(i.bytes, 24))]])],
        ['issuerAuth', [protectedBytes, unprotected, payload, signature]]
      ])],
      // Holder binding is not generated by this mock.
      ['deviceSigned', new Map([
        ['nameSpaces', new Tag(enc(new Map()), 24)],
        ['deviceAuth', new Map([['deviceSignature', [protectedBytes, new Map(), null, Buffer.alloc(64)]]])]
      ])]
    ])]],
    ['status', 0]
  ]);
  return Buffer.from(enc(response)).toString('base64url');
}

/** Plausible fake data per profile - clearly fictitious. */
const SAMPLE_DATA = {
  pid: {
    family_name: 'TEST-DOSSOU',
    given_name: 'Test Adjovi',
    birth_date: '1990-05-12'
  },
  birth_certificate: {
    family_name: 'TEST-DOSSOU',
    given_name: 'Test Adjovi',
    birth_date: '1990-05-12',
    birth_place: 'Cotonou',
    certificate_number: 'TEST-0000-1990-0001',
    father_name: 'TEST Koffi Dossou',
    mother_name: 'TEST Afi Dossou'
  }
};

module.exports = { createTestIssuer, buildDeviceResponse, SAMPLE_DATA };
