'use strict';

/**
 * Builds a SYNTHETIC mdoc DeviceResponse for local testing (mock wallet and
 * unit tests). It is signed by a throw-away key/certificate generated on the
 * fly, so it proves nothing about real citizens - it only exercises the RP.
 */

const crypto = require('crypto');
const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');
const { Encoder, Tag } = require('cbor-x');

const encoder = new Encoder({ useRecords: false, mapsAsObjects: false });
const enc = (v) => encoder.encode(v);

/** Self-signed P-256 issuer (acts as its own trust anchor). Needs the openssl CLI. */
function createTestIssuer(commonName = 'Sample RP Benin - TEST issuer') {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'sample-rp-benin-'));
  try {
    execFileSync(
      'openssl',
      ['req', '-x509', '-newkey', 'ec', '-pkeyopt', 'ec_paramgen_curve:P-256', '-nodes',
        '-keyout', path.join(dir, 'k.pem'), '-out', path.join(dir, 'c.pem'),
        '-subj', `/CN=${commonName}`, '-days', '30'],
      { stdio: 'ignore' }
    );
    const certPem = fs.readFileSync(path.join(dir, 'c.pem'));
    return {
      key: crypto.createPrivateKey(fs.readFileSync(path.join(dir, 'k.pem'))),
      certPem,
      certDer: new crypto.X509Certificate(certPem).raw
    };
  } finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

const isFullDate = (v) => typeof v === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(v);

/**
 * @param {object} o
 * @param {string} o.docType
 * @param {string} o.namespace
 * @param {object} o.elements   all issued elements { element_identifier: value } (all are in the MSO)
 * @param {string[]} [o.disclose] element identifiers actually presented (default: all)
 * @param {object} [o.issuer]   result of createTestIssuer() (omit => unsigned x5chain)
 * @param {Date}   [o.validFrom] / [o.validUntil]
 * @param {boolean} [o.tamper]  alter the first disclosed value after signing (negative test)
 * @returns {string} base64url DeviceResponse
 */
function buildDeviceResponse({ docType, namespace, elements, disclose, issuer, validFrom, validUntil, tamper }) {
  const now = Date.now();
  const items = Object.entries(elements).map(([id, value], digestID) => ({
    id,
    digestID,
    bytes: enc(new Map([
      ['digestID', digestID],
      ['random', crypto.randomBytes(16)],
      ['elementIdentifier', id],
      ['elementValue', isFullDate(value) ? new Tag(value, 1004) : value]
    ]))
  }));

  const valueDigests = new Map([[namespace, new Map(items.map((i) => [
    i.digestID,
    crypto.createHash('sha256').update(enc(new Tag(i.bytes, 24))).digest()
  ]))]]);

  const mso = new Map([
    ['version', '1.0'],
    ['digestAlgorithm', 'SHA-256'],
    ['valueDigests', valueDigests],
    ['deviceKeyInfo', new Map([['deviceKey', new Map([[1, 2], [-1, 1]])]])],
    ['docType', docType],
    ['validityInfo', new Map([
      ['signed', new Tag(new Date(now).toISOString().replace(/\.\d+Z/, 'Z'), 0)],
      ['validFrom', new Tag(new Date(validFrom || now - 3600e3).toISOString().replace(/\.\d+Z/, 'Z'), 0)],
      ['validUntil', new Tag(new Date(validUntil || now + 86400e3 * 30).toISOString().replace(/\.\d+Z/, 'Z'), 0)]
    ])]
  ]);

  // Tamper demo: the wallet "changes" a value after the issuer signed the digests.
  if (tamper) {
    const first = items.find((i) => !disclose || disclose.includes(i.id));
    const m = new Map([
      ['digestID', first.digestID],
      ['random', crypto.randomBytes(16)],
      ['elementIdentifier', first.id],
      ['elementValue', 'TAMPERED']
    ]);
    first.bytes = enc(m);
  }

  const payload = enc(new Tag(enc(mso), 24));
  const protectedBytes = enc(new Map([[1, -7]]));
  const unprotected = new Map();
  let signature = Buffer.alloc(64);
  if (issuer) {
    unprotected.set(33, issuer.certDer);
    const toSign = enc(['Signature1', protectedBytes, Buffer.alloc(0), payload]);
    signature = crypto.sign('sha256', toSign, { key: issuer.key, dsaEncoding: 'ieee-p1363' });
  }

  const response = new Map([
    ['version', '1.0'],
    ['documents', [new Map([
      ['docType', docType],
      ['issuerSigned', new Map([
        ['nameSpaces', new Map([[namespace, items.filter((i) => !disclose || disclose.includes(i.id)).map((i) => new Tag(i.bytes, 24))]])],
        ['issuerAuth', [protectedBytes, unprotected, payload, signature]]
      ])],
      // Holder binding is not generated by this mock.
      ['deviceSigned', new Map([
        ['nameSpaces', new Tag(enc(new Map()), 24)],
        ['deviceAuth', new Map([['deviceSignature', [protectedBytes, new Map(), null, Buffer.alloc(64)]]])]
      ])]
    ])]],
    ['status', 0]
  ]);
  return Buffer.from(enc(response)).toString('base64url');
}

const b64u = (b) => Buffer.from(b).toString('base64url');
const sha256 = (x) => crypto.createHash('sha256').update(x).digest();
const signJwt = (header, payload, key) => {
  const input = `${b64u(JSON.stringify(header))}.${b64u(JSON.stringify(payload))}`;
  return `${input}.${b64u(crypto.sign('sha256', Buffer.from(input), { key, dsaEncoding: 'ieee-p1363' }))}`;
};

/**
 * Builds a SYNTHETIC SD-JWT VC presentation (issuer-signed JWT + disclosures + KB-JWT).
 * @param {object} o
 * @param {string} o.vct
 * @param {object} o.claims      selectively-disclosable claims (all are signed into _sd)
 * @param {object} [o.plain]     claims that are NOT selectively disclosable (e.g. issuing_authority)
 * @param {string[]} [o.disclose] claim names actually presented (default: all)
 * @param {object} o.issuer      createTestIssuer() result
 * @param {string} o.aud         KB-JWT audience (the RP client_id as the wallet saw it)
 * @param {string} o.nonce       KB-JWT nonce
 * @param {boolean} [o.tamper]   alter the first presented value after signing (negative test)
 */
function buildSdJwtPresentation({ vct, claims, plain = {}, disclose, issuer, aud, nonce, validUntil, tamper }) {
  const holder = crypto.generateKeyPairSync('ec', { namedCurve: 'P-256' });
  const now = Math.floor(Date.now() / 1000);

  const disclosures = Object.entries(claims).map(([name, value]) => {
    const str = b64u(JSON.stringify([b64u(crypto.randomBytes(16)), name, value]));
    return { name, str, digest: b64u(sha256(str)) };
  });
  const payload = {
    iss: 'https://issuer.example.test',
    iat: now,
    exp: Math.floor((validUntil || Date.now() + 86400e3 * 30) / 1000),
    vct,
    cnf: { jwk: holder.publicKey.export({ format: 'jwk' }) },
    _sd_alg: 'sha-256',
    _sd: disclosures.map((d) => d.digest).sort(),
    ...plain
  };
  const header = { alg: 'ES256', typ: 'dc+sd-jwt', x5c: [issuer.certDer.toString('base64')] };
  const jwt = signJwt(header, payload, issuer.key);

  let presented = disclosures.filter((d) => !disclose || disclose.includes(d.name)).map((d) => d.str);
  if (tamper && presented.length) {
    const arr = JSON.parse(Buffer.from(presented[0], 'base64url'));
    arr[2] = 'TAMPERED';
    presented[0] = b64u(JSON.stringify(arr));
  }
  const signedPart = `${[jwt, ...presented].join('~')}~`;
  const kb = signJwt({ alg: 'ES256', typ: 'kb+jwt' }, { iat: now, aud, nonce, sd_hash: b64u(sha256(signedPart)) }, holder.privateKey);
  return signedPart + kb;
}

/**
 * Fictitious Benin-style persona (rulebook "Benin Display Simulation" tab). Values only: the
 * schema is the standard one. Clearly fake - never real citizen data.
 */
const PERSONA = {
  family_name: 'KOSSI', given_name: 'Jean', birth_date: '1990-05-12',
  birth_place: 'Cotonou', birth_country: 'BJ', birth_state: 'Littoral', birth_city: 'Cotonou', gender: 1
};
const SAMPLE_DATA = {
  pid: {
    ...PERSONA,
    age_over_18: true, age_in_years: 36, age_birth_year: 1990,
    nationality: ['BJ'], resident_address: '12 Rue des Cocotiers, Cotonou, BJ',
    document_number: 'CNIB123456789', issuance_date: '2025-01-15', expiry_date: '2035-01-14',
    issuing_authority: 'ANIP', issuing_country: 'BJ',
    personal_administrative_number: '1234567890123'
  },
  birth_certificate: {
    // selectively disclosable (rulebook: SD = Yes)
    claims: {
      ...PERSONA,
      mother_family_name: 'AGBOSSOU', mother_given_name: 'Marie',
      father_family_name: 'KOSSI', father_given_name: 'Koffi',
      birth_record_reference: 'TEST-ACTE-1990-000123', document_number: 'TEST-BC-0001'
    },
    // not selectively disclosable (rulebook: SD = No)
    plain: { issuance_date: '2025-02-01', issuing_authority: 'ANIP' }
  }
};

module.exports = { createTestIssuer, buildDeviceResponse, buildSdJwtPresentation, SAMPLE_DATA };
